### ISSUE TITLE
Package/Assembly Naming

### ISSUE THREAD

**Issue by rowanmiller** [ErikEJ/EntityFramework7.SqlServerCompact#129]
We just posted a doc with some guidelines we are adopting for naming https://github.com/aspnet/EntityFramework/wiki/NuGet-Package-Naming. It would be great if the compact provider could follow these too.

BTW we haven't made the changes in our code base yet, but we will shortly.

**Comment by ErikEJ** [comment]
@rowanmiller Will do, so: EntityFramework7.SqlServerCompact, then?

And how about the namespace, I use: ErikEJ.Data.Entity.SqlServerCe 

It was System.Data.Entity.SqlServerCompact in EF6

**Comment by rowanmiller** [comment]
I would use `Microsoft.Data.Entity.*` which is what we use in our providers. BTW check out https://github.com/aspnet/EntityFramework/pull/2503 as we have stopped nesting things in a provider specific namespace.

**Comment by ErikEJ** [comment]
So you suggest simply using  Microsoft.Data.Entity as namespace, for example  for the SqlCeDatabase class: Microsoft.Data.Entity.SqlCeDatabase ?

**Comment by rowanmiller** [comment]
You would follow where the base type is in the core package. So `Microsoft.Data.Entity.Storage.SqlCeDatabase` since it inherits from `Microsoft.Data.Entity.Storage.RelationalDatabase` (which in turn inherits from `Microsoft.Data.Entity.Storage.Database`)

**Comment by ErikEJ** [comment]
@rowanmiller Thanks!

**Comment by ErikEJ** [comment]
@rowanmiller  Following the base type does not seem to be implemented (yet?) in the SqlServer provider!?

    namespace Microsoft.Data.Entity.SqlServer
    {
        public class SqlServerDatabase : RelationalDatabase

**Comment by rowanmiller** [comment]
@ErikEJ ah, you are correct. Moving things has only got as far as the Relational assembly so far. The other stuff will move as well :smile:.
