### ISSUE TITLE
Reference to type 'RelationalDbContextOptionBuilder'   [dnx451] (windows)

### ISSUE THREAD

**Issue by dvdcrr77** [ErikEJ/EntityFramework7.SqlServerCompact#213]
Configuring the UseSqlCe inside DbContext.  

The error claims it is defined in 'EntityFramework.Relational'

**Comment by ErikEJ** [comment]
Hmmm... Could you share some code and other details?

**Comment by dvdcrr77** [comment]
Yes, 

Issue inside V Studio Code when accessing the builder inside a data context.
"EntityFramework.SqlServerCompact40": "7.0.0-beta6"
"DNX Runtime 1.0.0-beta-15330"

![vscodesnippet](https://cloud.githubusercontent.com/assets/13968716/9641312/06db81e2-51ae-11e5-9641-5bcd28819f5b.PNG)

**Comment by ErikEJ** [comment]
SQL Server Compact only works with Full Desktop .NET - also you cannot mix beta 8 and beta 6 bits.

**Comment by dvdcrr77** [comment]
I did read desktop only

**Comment by dvdcrr77** [comment]
Connection test passed under DNX Runtime beta6-12256 using EntityFramework 7.0.0-beta6 and it works well,  migrations even seem to work from code which is a bonus , after attempting to use the migration tool.
