### ISSUE TITLE
Could not load type error

### ISSUE THREAD

**Issue by nicolasr75** [ErikEJ/EntityFramework7.SqlServerCompact#222]
In my desktop test project I updated all nuget packages to newest beta 8 versions except for
EntityFramework.Relational which EntityFramework7.SqlServerCompact40 requires to be exactly 7.0.0-beta8-15623. So I left it at that specific version.
However, there now seems to be some incompatibility with the newest EF packages. I get the following error:

Could not load type
'Microsoft.Data.Entity.Query.ExpressionVisitors.ReducingExpressionVisitor'
from assembly 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=null'.

I don't get this error when I use SqlServer instead of SqlServerCompact40 and update the EntityFramework.Relational package. 
What do you think?

**Comment by ErikEJ** [comment]
The beta 8 feed that holds EntityFramework.SqlServer is always in sync with the latest bits, where as I am always lagging behind the latest daily. So remove all NuGet references and add EntityFramework.SqlServerCompact40 -Pre to your project so all dependencies match

**Comment by nicolasr75** [comment]
Thanks that fixed it.
