### ISSUE TITLE
EF7 SQL Server Compact Create a Model from an existing database

### ISSUE THREAD

**Issue by ChangedHourly** [ErikEJ/EntityFramework7.SqlServerCompact#234]
Hi, I have the SQLCe provider working, creating new database and opening existing. I have tried to create a model from an existing database but have hit two problems. The first was when I tried to install EntityFramework.SqlServerCompact40.Design -Pre:

PM> install-package entityframework.sqlservercompact40.design -pre
Attempting to gather dependencies information for package 'entityframework.sqlservercompact40.design.7.0.0-beta7a' with respect to project 'EF7DataLayer', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'entityframework.sqlservercompact40.design.7.0.0-beta7a' with DependencyBehavior 'Lowest'
install-package : Unable to resolve dependencies. 'EntityFramework.Relational.Design 7.0.0-beta8-15723' is not compatible with 'EntityFramework.Commands 7.0.0-beta8-15723 constraint: EntityFramework.Relational.Design (≥ 7.0.0-beta8-15723)', 'EntityFramework.SqlServerCompact40.Design 7.0.0-beta7a 
constraint: EntityFramework.Relational.Design (= 7.0.0-beta7)'.
At line:1 char:1
+ install-package entityframework.sqlservercompact40.design -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I then installed the package anyway by ignoring the dependencies, just to see if it might work. I then got this error when I tried to run the scaffold:

PM> scaffold-dbcontext -connection "DataSource=C:\Users\Patrick\Documents\z.sdf" -provider entityframework.sqlservercompact40
scaffold-dbcontext : Exception calling "CreateInstance" with "8" argument(s): "Type 'System.Management.Automation.SwitchParameter' in assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable."
At line:1 char:1
+ scaffold-dbcontext -connection "DataSource=C:\Users\Patrick\Documents ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Scaffold-DbContext], MethodInvocationException
    + FullyQualifiedErrorId : SerializationException,Scaffold-DbContext

Any ideas on  what I should try?

Thanks

**Comment by ErikEJ** [comment]
Great you got it working - you should reference either only nuget.org or the myget feed, not both at the same time.

**Comment by ChangedHourly** [comment]
Hmm, I am using EF7 nightly builds, current version 7.0.0-beta8-15723. If I try to install EntityFramework.SqlServerCompact40 from nugget.org then I get:

Attempting to gather dependencies information for package 'EntityFramework.SqlServerCompact40.7.0.0-beta7a' with respect to project 'EF7DataLayer', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'EntityFramework.SqlServerCompact40.7.0.0-beta7a' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'EntityFramework.Relational 7.0.0-beta8-15723' is not compatible with 'EntityFramework.Commands 7.0.0-beta8-15723 constraint: EntityFramework.Relational (≥ 7.0.0-beta8-15723)', 'EntityFramework.Relational.Design 7.0.0-beta8-15723 constraint: EntityFramework.Relational (≥ 7.0.0-beta8-15723)', 'EntityFramework.SqlServer 7.0.0-beta8-15723 constraint: EntityFramework.Relational (≥ 7.0.0-beta8-15723)', 'EntityFramework.SqlServerCompact40 7.0.0-beta7a constraint: EntityFramework.Relational (= 7.0.0-beta7)'.

Do I need to revert to an earlier nightly build?

**Comment by ErikEJ** [comment]
Sounds like you are mixing beta7a and beta8 bits. Make sure to install only beta8 bits in your project, and that only beta8 bits are referenced by your code.

**Comment by ChangedHourly** [comment]
I think during the course of events I probably did have the beta7/8 bits mixed (my second comment was probably made at that time). I am quite sure I have that sorted now, but I still get an error:

Attempting to gather dependencies information for package 'EntityFramework.SqlServerCompact40.Design.7.0.0-beta8-328' with respect to project 'EF7DataLayer', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'EntityFramework.SqlServerCompact40.Design.7.0.0-beta8-328' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'EntityFramework.Relational 7.0.0-beta8-15723' is not compatible with 'EntityFramework.Commands 7.0.0-beta8-15723 constraint: EntityFramework.Relational (≥ 7.0.0-beta8-15723)', 'EntityFramework.Relational.Design 7.0.0-beta8-15723 constraint: EntityFramework.Relational (≥ 7.0.0-beta8-15723)', 'EntityFramework.SqlServer 7.0.0-beta8-15723 constraint: EntityFramework.Relational (≥ 7.0.0-beta8-15723)', 'EntityFramework.SqlServerCompact40 7.0.0-beta8-328 constraint: EntityFramework.Relational (= 7.0.0-beta8-15719)'.

All the references are to beta8 packages now, but the last constraint seems to be for an exact build which I think may be the problem.

**Comment by ErikEJ** [comment]
It would be useful if your could share your packages.config file, but I think the version of EF.Commands installed is too new - see the (just updated) instructions here: Install-Package EntityFramework.Commands -Pre -Version 7.0.0-beta8-15719
 
     Install-Package EntityFramework.Commands -Pre -Version 7.0.0-beta8-15719

**Comment by ChangedHourly** [comment]
I was going to mention in my previous post that I had tried installing EntityFramework.Commands15719 but I couldn't remember the error it gave me. I have tried again and I also had to move the EntityFramework.Relational back to 15719. I'm afraid I'm still then back to the following error:

PM> scaffold-dbcontext -connection "Data Source=C:\Users\Patrick\Documents\z.sdf" -provider EntityFramework.SqlServerCompact40
scaffold-dbcontext : Exception calling "CreateInstance" with "8" argument(s): "Type 'System.Management.Automation.SwitchParameter' in assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable."
At line:1 char:1
+ scaffold-dbcontext -connection "Data Source=C:\Users\Patrick\Document ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Scaffold-DbContext], MethodInvocationException
    + FullyQualifiedErrorId : SerializationException,Scaffold-DbContext


packages.config below:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework.Commands" version="7.0.0-beta8-15719" targetFramework="net46" />
  <package id="EntityFramework.Core" version="7.0.0-beta8-15723" targetFramework="net46" />
  <package id="EntityFramework.Relational" version="7.0.0-beta8-15719" targetFramework="net46" />
  <package id="EntityFramework.Relational.Design" version="7.0.0-beta8-15719" targetFramework="net46" />
  <package id="EntityFramework.SqlServer" version="7.0.0-beta8-15719" targetFramework="net46" />
  <package id="EntityFramework.SqlServerCompact40" version="7.0.0-beta8-328" targetFramework="net46" />
  <package id="EntityFramework.SqlServerCompact40.Design" version="7.0.0-beta8-328" targetFramework="net46" />
  <package id="Ix-Async" version="1.2.5" targetFramework="net46" />
  <package id="Microsoft.AspNet.Razor" version="4.0.0-beta8-15611" targetFramework="net46" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0-beta1-20150812-01" targetFramework="net46" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.1.0-beta1-20150907-01" targetFramework="net46" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="1.1.0-beta1-20150907-01" targetFramework="net46" />
  <package id="Microsoft.Framework.Caching.Abstractions" version="1.0.0-beta8-15583" targetFramework="net46" />
  <package id="Microsoft.Framework.Caching.Memory" version="1.0.0-beta8-15583" targetFramework="net46" />
  <package id="Microsoft.Framework.Configuration" version="1.0.0-beta8-15586" targetFramework="net46" />
  <package id="Microsoft.Framework.Configuration.Abstractions" version="1.0.0-beta8-15586" targetFramework="net46" />
  <package id="Microsoft.Framework.Configuration.Binder" version="1.0.0-beta8-15586" targetFramework="net46" />
  <package id="Microsoft.Framework.DependencyInjection" version="1.0.0-beta8-15574" targetFramework="net46" />
  <package id="Microsoft.Framework.DependencyInjection.Abstractions" version="1.0.0-beta8-15574" targetFramework="net46" />
  <package id="Microsoft.Framework.Logging" version="1.0.0-beta8-15575" targetFramework="net46" />
  <package id="Microsoft.Framework.Logging.Abstractions" version="1.0.0-beta8-15575" targetFramework="net46" />
  <package id="Microsoft.Framework.OptionsModel" version="1.0.0-beta8-15574" targetFramework="net46" />
  <package id="Microsoft.SqlServer.Compact" version="4.0.8876.1" targetFramework="net46" />
  <package id="Remotion.Linq" version="2.0.0-beta-002" targetFramework="net46" />
  <package id="System.Collections" version="4.0.11-beta-23302" targetFramework="net46" />
  <package id="System.Collections.Immutable" version="1.1.37-beta-23109" targetFramework="net46" />
  <package id="System.Diagnostics.Debug" version="4.0.0-beta-23109" targetFramework="net46" />
  <package id="System.Globalization" version="4.0.0-beta-23109" targetFramework="net46" />
  <package id="System.Linq" version="4.0.0-beta-23109" targetFramework="net46" />
  <package id="System.Reflection.Metadata" version="1.1.0-alpha-00012" targetFramework="net46" />
  <package id="System.Resources.ResourceManager" version="4.0.0-beta-23109" targetFramework="net46" />
  <package id="System.Runtime" version="4.0.0-beta-23109" targetFramework="net46" />
  <package id="System.Runtime.Extensions" version="4.0.0-beta-23109" targetFramework="net46" />
  <package id="System.Threading" version="4.0.0" targetFramework="net46" />
  <package id="SystemWrapper" version="0.4" targetFramework="net46" />
</packages>

**Comment by ErikEJ** [comment]
Could you indent packages.config - could be a typo / syntax issue with your command?

**Comment by ChangedHourly** [comment]
I'm afraid this amateur is having trouble! Has this worked?

[image](https://cloud.githubusercontent.com/assets/11739945/9981795/0b94e934-5fbf-11e5-954e-8e610c19502b.png)

**Comment by ErikEJ** [comment]
Or maybe my docs are wrong!

**Comment by ErikEJ** [comment]
I can see the packages.config now, your EF Core package is too new!

**Comment by ErikEJ** [comment]
I think the command should be changed to: 

    scaffold-dbcontext "DataSource=C:\Users\Patrick\Documents\z.sdf"  entityframework.sqlservercompact40

**Comment by ChangedHourly** [comment]
Sorry, but I still get:

PM> scaffold-dbcontext "DataSource=C:\Users\Patrick\Documents\z.sdf"  entityframework.sqlservercompact40
scaffold-dbcontext : Exception calling "CreateInstance" with "8" argument(s): "Type 'System.Management.Automation.SwitchParameter' in assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable."
At line:1 char:1
+ scaffold-dbcontext "DataSource=C:\Users\Patrick\Documents\z.sdf"  ent ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Scaffold-DbContext], MethodInvocationException
    + FullyQualifiedErrorId : SerializationException,Scaffold-DbContext
 
Packages.config:

![image](https://cloud.githubusercontent.com/assets/11739945/9982098/4873289e-5fc8-11e5-9d13-b7b971c6d830.png)

**Comment by ErikEJ** [comment]
I will investigate...

**Comment by ErikEJ** [comment]
I am able to repro - I have logged an issue here: https://github.com/aspnet/EntityFramework/issues/3178

**Comment by ErikEJ** [comment]
FYI - using just the beta 7 bits from NuGet Works fine - why do you need the daily builds?

**Comment by ChangedHourly** [comment]
Thanks for the support, I will hopefully get to try the beta7 later tonight. There are a couple of features in the latest builds that are currently WIP which are important to me and I am trying to keep up with, namely TPH and the GraphBehavior.

**Comment by ChangedHourly** [comment]
Progress... With beta7 I now get:

PM> scaffold-dbcontext -connection "Data Source=C:\Temp\z.sdf" -provider EntityFramework.SqlServerCompact40
The type initializer for 'System.Collections.Immutable.ImmutableSortedSet`1' threw an exception.

Packages:
![image](https://cloud.githubusercontent.com/assets/11739945/10003508/b269a804-60a4-11e5-966b-1d795e2b2bc5.png)

**Comment by ErikEJ** [comment]
Remove all references, delete your packages folder and start over - System.Collections.Immutable must be version 1.1.36

**Comment by ErikEJ** [comment]
I was a bug in EntityFramework.Commands, and will be fixed in my next "daily"/refresh

**Comment by ErikEJ** [comment]
@ChangedHourly I have released a new build that should contain the fix

**Comment by ChangedHourly** [comment]
OK, I think I still need some help regarding the packages though. I can see your new build 7.0.0-beta8-330. Am I correct in assuming this needs to be installed with EF beta8 bits (re don't mix beta7/8 bits)? If so, then what about System.Collections.Immutable, does that still have to be 1.1.36?

**Comment by ErikEJ** [comment]
Start with a blank project, and follow the instructions here: https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/wiki/Using-EF7-with-SQL-Server-Compact-in-Traditional-.NET-Applications-(daily-builds) - and of course I would appreciate any feedback you may have if the instructions are unclear!
