### ISSUE TITLE
VB Project Support

### ISSUE THREAD

**Issue by anandmukundan** [ErikEJ/EntityFramework7.SqlServerCompact#242]
When using the EF update-database commands in a VB project does not seem to result in any action taking place.

**Comment by ErikEJ** [comment]
What version and what VB project type? Could you share a repro project?

**Comment by anandmukundan** [comment]
I am using VS2015. When using C# (same machine, completely new test projects in both cases), Update database generate a new DB and tables. In VB, it just returns "done", but does not do anything. I have uploaded a sample project (with packages removed due to  size) at http://1drv.ms/1hBHwlX

**Comment by ErikEJ** [comment]
Sorry for the trouble, the reverse Engineering tools currently does not support VB, I think the current planis to do so eventually  - I have logged and issue here: https://github.com/aspnet/EntityFramework/issues/3417

**Comment by midnait** [comment]
ErikEJ plz, see https://github.com/aspnet/EntityFramework/issues/4210

I want use your SQLServerCE provider + VB  
=D

Hugs

**Comment by ErikEJ** [comment]
@midnait  Adding VB support is not something I can do...
