### ISSUE TITLE
Error update database using IdentityDbContext

### ISSUE THREAD

**Issue by oswaldomilet** [ErikEJ/EntityFramework7.SqlServerCompact#271]
When I tried to "dnx ef database update" I got this error:

"The property 'LockoutEnd' on entity type 'Server.Web.Models.ApplicationUser' has not been added to the model or ignored."

**Comment by ErikEJ** [comment]
OK.Could you share a lilltle more info. What data type is LockoutEnd? I suspect it could be an unsupported data type. Also, what EF7 version do you use? and you are aware that the SQL CE provider does not support DNX Core?

**Comment by ErikEJ** [comment]
It looks like you can try to ignore "Lockoutend" which of unsupported type "DateTimeOffset"

**Comment by ErikEJ** [comment]
Closing as there seems to be nothing to change in the SQL CE provider - feel free to re-open if you disagree
